### PR TITLE
[MPS-28685] Add Community Discord

### PR DESCRIPTION
**Pull request by MattIPv4**
Relates to https://youtrack.jetbrains.com/issue/MPS-28685

### CODE REVIEW

**Comment by orangy** [comment]
JetBrains doesn't maintain Discord and no official support for it is planned. Please don't submit any more PRs to our public pages. The badge you use cannot be accepted since it is not our official resource.

**Comment by MattIPv4** [comment]
@orangy We've been Goldberg the Discord will soon be linked on the MPS open source web page, why can it not therefor be linked on the repo?

**Comment by orangy** [comment]
Even if the MPS team is planning to put a link on a web page, it's something that will go through many checks, including design, company identity, etc. The link to the 3rd party resource can't have a `JB` icon next to it. Also, you submitted this PR to a dozen of our projects, which looks like link spam.

**Comment by MattIPv4** [comment]
@orangy Ah makes sense, we'll happily remove the JB icon logo if that is leading to issues. PRs were made on all applicable projects and each one was unique as they all is different invite links for analytical purposes if merged. Based on that's am I okay to create a new PR here addressing the MPS ticket with the fix for no JB logo?

**Comment by orangy** [comment]
No, these PRs will not be merged. Please don't do it.

**Comment by MattIPv4** [comment]
@orangy what is the reason why a new PR that has just the link added under the resources section to address the issue on YouTrack would not be accepted?
I would like to get this resolved so that the Discord community can be shared with more users of the open source projects.

**Comment by orangy** [comment]
That issue was created by you, so a PR to add a link to a resource you presumably have some interest in growing cannot be justified by an issue. I'm not against growing community resources, you're welcome to do so. But we cannot add links randomly to any such resources, because then we will have to add links to all such resources.

**Comment by MattIPv4** [comment]
@orangy We are already linked from some JetBrains pages which is why we decided to PR more, and hopefully will soon also on the main MPS site. Once added to the MPS site, can a PR then be made here?

**Comment by orangy** [comment]
I never saw a JetBrains page other than _a list of community resources_ (or plugins portal) linking specifically to Discord. Can you show me them?

**Comment by MattIPv4** [comment]
@orangy Yes, under the community resources list for ring ui, which is almost identical to this PR.
I fully understand that the badges aren't a something that can be merged, but adding the link to resources lists seems more sensible?

**Comment by MattIPv4** [comment]
@orangy Hm okay. We took the acceptance of the ring ui PR, the update that we would be added to the MPS site and the large presence of JB staff in the Discord as signs that we are slightly above random link status. We even had JetBrains promoting us on Twitter before. I'll await us being added to the MPS site before pursuing this further I guess...

**Comment by orangy** [comment]
> We even had JetBrains promoting us on Twitter before
I wonder where did you see it? Maybe it was not JetBrains as a company, but rather some specific employee? We all have our opinions and they are not necessarily representing employer's, you know :)

**Comment by MattIPv4** [comment]
@orangy The promotion was done through the official PyCharm account.

Back when this resource was first created we got explicit permission from JetBrains to exist. This led to the project being shared internally which resulted in the large and relatively active JB presence in the server.

With that in mind we recently decided to pursue being added to the JB site in assorted places. With MPS accepting us to be added to their pages we then aimed at the open source side of JB on GitHub.

We created the PR on ring ui along with some other projects and when the link on ring ui was merged we took this as a good sign to PR to more projects to be listed.

Whilst I fully understand that the badges can't be done, in our well known with JB status as a resource, being linked from relevant places does seem reasonable in my mind? We aren't just a random resource unknown by JB.

**Pull request closed without merging**
