### PR TITLE
Add support for different HTTP Methods

### PR DESCRIPTION
**Pull request by bkolb**
* expose http method from the http request
* allow RequestHandler to declare supported methods

### CODE REVIEW

**Review by qradimir — COMMENTED** [review]
Hello, @bkolb! Thank you for the pull request! 

I have some questions before we can merge it.

* Have you considered using enumeration data type instead of sub-concepts of HttpMethod to express different request methods? 
* Generator of [canHandle](http://127.0.0.1:63320/node?ref=r%3A54a5f1cc-4056-4ebe-b91a-271cac338c49%28jetbrains.mps.ide.httpsupport.generator.template.main%40generator%29%2F3520791039920636890&project=MPS) method linearly checks for each request method. Wouldn't it be more efficient to generate a HashSet's lookup there instead or even a switch-statement? Also, it compares the request method by ignoring their case however it seems that methods are case-sensitive by the specification.
* There are already exists a bunch of tests for HTTP request DSL [here](http://127.0.0.1:63320/node?ref=r%3A9e9ac0ea-b755-4d57-b406-d0cd74445963%28jetbrains.mps.ide.httpsupport.tests.lang%40tests%29%2F529363524336376150&project=MPS). Is it possible to add new tests for the introduce construction? I think it would be good to test here if other request methods (apart from `GET` that was only supported before) are handled well.
* The handlers that written before the change was consuming only requests of `GET` method, while after the change they will become consuming requests of any method, which might be inconsistent for some requests. Shouldn't we introduce a migration script that will restore the original semantics of old request handlers? @ashatalin, It seems that to author an idempotent automatic migration some additional complications are required. From your perspective, should we care about keeping the behaviour in this case, or we might just mention in the what's new that behaviour is changed?

**Comment by ashatalin** [comment]
I think, it's good to have some migration in order to not change the code of our clients manually. On the other side, we do not have too many users using this part of MPS. So, may be some kind of intention may handle such situations if we cannot afford writing proper migration in this case.

**Comment by qradimir** [comment]
JFR, I see the following approach for the automatic migration:

1. Constrain that the request handler's method list has to be non-empty, so users are required to specify at least one method for the handler to make it correct;
2. Introduce an automatic migration that adds GET request method to each of the present request handlers;
3. Introduce a node factory that adds GET request method to newly created request handlers.

@bkolb what do you think about this solution? Do you have a case where a request handler has to handle a request on an arbitrary request method, or it's fine to constrain the `handledMethods` role to be non-empty?

**Comment by bkolb** [comment]
Hi @qradimir,

thank you for havig a look!

See comments inline.

Best, 
Bernd

> 
> * Have you considered using enumeration data type instead of sub-concepts of HttpMethod to express different request methods?

I would be fine with an Enum as well. I typically use Subconcepts as they can be easily extended. Although not a common use case, the protocol itself allows for that. 

> * Generator of [canHandle](http://127.0.0.1:63320/node?ref=r%3A54a5f1cc-4056-4ebe-b91a-271cac338c49%28jetbrains.mps.ide.httpsupport.generator.template.main%40generator%29%2F3520791039920636890&project=MPS) method linearly checks for each request method. Wouldn't it be more efficient to generate a HashSet's lookup there instead or even a switch-statement? Also, it compares the request method by ignoring their case however it seems that methods are case-sensitive by the specification.

I like the idea with the switch/case. Will provide an update.

> * There are already exists a bunch of tests for HTTP request DSL [here](http://127.0.0.1:63320/node?ref=r%3A9e9ac0ea-b755-4d57-b406-d0cd74445963%28jetbrains.mps.ide.httpsupport.tests.lang%40tests%29%2F529363524336376150&project=MPS). Is it possible to add new tests for the introduce construction? I think it would be good to test here if other request methods (apart from `GET` that was only supported before) are handled well.

Sure! Was not aware of them. I will add test cases.

> * The handlers that written before the change was consuming only requests of `GET` method, while after the change they will become consuming requests of any method, which might be inconsistent for some requests. Shouldn't we introduce a migration script that will restore the original semantics of old request handlers? @ashatalin, It seems that to author an idempotent automatic migration some additional complications are required. From your perspective, should we care about keeping the behaviour in this case, or we might just mention in the what's new that behaviour is changed?

I think I can handle this in the generator, if I introduce a special ANY Method. I will update this as well.

**Comment by bkolb** [comment]
> @bkolb what do you think about this solution? Do you have a case where a request handler has to handle a request on an arbitrary request method, or it's fine to constrain the `handledMethods` role to be non-empty?

Well, any is certainly nice-to-have. One could argue, that this should not be supported. On the other hand, this allows to check the method in the handler itself and by that simplify the code...

**Comment by bkolb** [comment]
OK. Seems that Netty does not support custom methods anyway. So i will change the HTTPMethod to an enum

**Comment by bkolb** [comment]
Changes are pushed. Can you please have a second look?

**Comment by qradimir** [comment]
@bkolb Looks good to me. Will merge it soon!

**Pull request merged**
