### PR TITLE
MPS-33490 using the 'subscript' script-kind style is non-intuitive

### PR DESCRIPTION
**Pull request by aamt74**
Conform discussion on [youtrack](https://youtrack.jetbrains.com/issue/MPS-33490), I will there also post my contributions to the User Guide to resolve this issue completely.

### CODE REVIEW

**Comment by maros-sandor** [comment]
I checked the pull request, I see 2 issues:

1. The name "super-/subscript" seems a bit awkward to me, maybe the two consecutive special characters is not ideal.
2. You only modified the generated file. The way to do it properly is to make the change in MPS in the concept CellLayout_Superscript and rebuild the language. You will notice the file java re-generates itself and there will be more additional changes (in the model xml file and checksum files)

**Comment by aamt74** [comment]
Thanks for the feedback. I changed the name to "super/subscript", and modified it the proper way now. Indeed several changes were induced.

Unfortunately I cannot upload the changes, because after getting the upstream changes (move to RC 2021.2), I can no longer run MPS from IDEA. (Errors like: Exception in thread "pool-4-thread-10" java.lang.IllegalArgumentException: Argument for @NotNull parameter 'name' of jetbrains/mps/generator/plan/PlanIdentity.<init> must not be null)

I asked a question about it in slack, once I have this solved I will post my changes.

**Comment by aamt74** [comment]
I screwed up with branches and accounts in github. Sorry about that. I made a new PR [here](https://github.com/JetBrains/MPS/pull/62). This PR can be closed.

**Comment by ashatalin** [comment]
Obsolete

**Pull request closed without merging**
