### PR TITLE
Use character instead of one-character string where available

### PR DESCRIPTION
**Pull request by smmribeiro**
There're several places where a "one-character" string is created to be passed to a method that accepts a character directly. This last version is normally faster (and has not the overhead of creating the String object).
In this commit, I replaced most usages (ignoring files signalled as generated) for String.indexOf, String.lastIndexOf and StringBuilder.append .

### CODE REVIEW

**Comment by smmribeiro** [comment]
#**21** is **21** days old :-)

**Comment by smmribeiro** [comment]
No one looked into this pull request in the last three months and now it has conflicts, so I'll close it.
This wouldn't make a big difference in performance, but I believe that any little thing helps (and this is an almost "free lunch" optimisation).
:-(

**Comment by oscarmarcelo88** [comment]
Hello, @smmribeiro! 
I am Oscar, the Product Marketing Manager of MPS. 
First of all, sorry for didn't check the pull request on time. We have been very busy with the version 2017.2, but this is not an excuse. 
I invite you to solve the conflicts, and I will make sure that someone checks it out. 

We appreciate your contribution in MPS!

Best,

**Comment by smmribeiro** [comment]
Hello @oscarmarcelo88 ,

Thank you for the feedback (sometimes it's just that that is needed). I'll try to redo the pull request until the end of this week.

Regards,

Sérgio Ribeiro
Porto - Portugal

**Comment by oscarmarcelo88** [comment]
Perfect!
Please ping me when you have it ready.

Best,

**Comment by smmribeiro** [comment]
@oscarmarcelo88, I've fixed the conflicts and opened a new PR: [PR#23](https://github.com/JetBrains/MPS/pull/23).

Regards,
Sérgio.

**Comment by oscarmarcelo88** [comment]
Got it!
Let me process it with someone from the team.

Thanks!
Oscar

**Comment by smmribeiro** [comment]
Thank you @oscarmarcelo88 .
I'm now on my vacations, but I have one or more thoughts that may improve MPS... I'll try to work on them and create new PR's for you guys :-)

**Comment by oscarmarcelo88** [comment]
That will be awesome @smmribeiro! If you need any kind of support for the PR let us know.

Enjoy your vacations,
Oscar Rodriguez

**Pull request closed without merging**
